[package]
name = "tee"
version = "0.1.1"
authors = ["softprops <d.tangren@gmail.com>", "SOFe <sofe2038@gmail.com>"]
description = "An adapter for readers which delegate reads to a writer"
repository = "https://github.com/SOF3/tees"
keywords = ["io"]
license = "MIT"
